apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  type: LoadBalancer   # Set NodePort if you prefer, but LoadBalancer exposes to the internet
  selector:
    app: blog-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
